title: PMLCourse-sut
description: Princiles of Machine Learning, 2025 

remote_theme: just-the-docs/just-the-docs

search_enabled: false

nav_order: 1  # Controls sidebar order

nav:
  - title: Home
    url: /
    nav_order: 1
  - title: Syllabus
    url: /syllabus
    nav_order: 2
  - title: Resources
    url: /resources
    nav_order: 3



# Custom CSS
assets:
  stylesheets:
    - assets/css/custom.css


# Color customization
color_scheme: light  # Options: light, dark

logo: "/assets/Images/Sharif_logo.png"

favicon_ico: "/assets/Images/PML_favicon.png"


footer_content: "© 2025 My Documentation Site. All rights reserved."
